global using CommonBasicLibraries.CollectionClasses;
global using NewTestament5DayLibrary.Core.Models;
global using CommonBasicLibraries.BasicDateTimeProcesses;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using rr = NewTestament5DayLibrary.Core.Resources;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;